# Welcome to sun-ming' personal page!
lang: zh_CN
title: 孙铭的个人网站
author: sun-ming
email: forkmail@qq.com
description: > 
  孙铭，90后程序猿一枚，热爱分享，喜欢折腾，乐于探索，勇于挑战自我，对新事物充满热情，广交天下有志之士，共谋IT发展大计。
baseurl: ""
url: "http://sun-ming.github.io"
github_username:  sun-ming
twitter_username: ""

minima:
  date_format: "%b %-d, %Y"

timezone: Asia/Shanghai

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 15
paginate_path: "/blog/p:num"
